### ISSUE TITLE
无法使用 compilerPath“D:\Mingw64\bin\g++.exe”解析配置

### ISSUE THREAD

**Issue by Nieianyue** [VSCodeConfigHelper/v4#1]
无法使用 compilerPath“D:\Mingw64\bin\g++.exe”解析配置。 请改用“D:\Mingw64\bin\gcc.exe”。

**Comment by Guyutongxue** [comment]
您的MinGWC++编译器（仅有C编译器）。建议：
- 以C语言配置；
- 或重新下载MinGW，例如工具提供的下载链接。
