### ISSUE TITLE
无法在M1 的MacBook Air macOS13.1上使用

### ISSUE THREAD

**Issue by kingwingfly** [VSCodeConfigHelper/v4#16]
<img width="636" alt="image" src="https://user-images.githubusercontent.com/38573173/201972477-c65f5eb7-f8ea-437c-88e1-655559893bd2.png"> 

打开后没有显示任何东西。 
macOS版本是13.1，M1芯片。 
之前没用过，不知道是系统的问题还是app对M1不支持。

**Comment by EnTeR-uSeRnAmEs** [comment]
我昨天刚刚在m1的Ventura系统使用4.0.3版本，没有发现异常

**Comment by kingwingfly** [comment]
> 

会不会是因为我的vscode是用homebrew装的。。。你的vscode是咋装的鸭

**Comment by Guyutongxue** [comment]
> > 
> 
> 会不会是因为我的vscode是用homebrew装的。。。你的vscode是咋装的鸭

一般是从官网安装。但这个应该不影响软件的启动过程。

目前的问题像是 WebView 无法加载。

**Comment by kingwingfly** [comment]
> 你可以试一试用 CLI：
> 
> ```shell
> vscch.app/Contents/MacOS/vscch --cli
> ```

命令行可以用，并且打出`hello world`（好耶！），但是我想看二次元小姐姐，呜呜呜。算了，其实我昨天已经熬夜配置好了。  谢谢啦！
