### ISSUE TITLE
如何进行多文件编译运行啊

### ISSUE THREAD

**Issue by WindyLuf** [VSCodeConfigHelper/v4#21]
我是在项目文件夹0下面的某个文件夹1下面，写了三个文件，在F6运行时报错。是不是不支持多文件运行呢。

**Comment by Guyutongxue** [comment]
RTFM.
https://v4.vscch.tk/docs/#%E5%85%B3%E4%BA%8E%E6%9C%AC%E8%BD%AF%E4%BB%B6
