### ISSUE TITLE
编译器版本信息包含中文（TDM-GCC）无法识别

### ISSUE THREAD

**Issue by T-Atlas** [VSCodeConfigHelper/v4#22]
选到了bin目录下无法识别gcc

**Comment by Guyutongxue** [comment]
理论上是支持的。请附日志文件（位于 `%USERPROFILE%\AppData\Roaming\vscch`）

**Comment by T-Atlas** [comment]
[vscch_20230128214018.log](https://github.com/VSCodeConfigHelper/v4/files/10527540/vscch_20230128214018.log)
[vscch_20230128214556.log](https://github.com/VSCodeConfigHelper/v4/files/10527541/vscch_20230128214556.log)

**Comment by T-Atlas** [comment]
`PS C:\Users\LianJunhong\Desktop> gcc --version
gcc.exe (tdm64-1) 10.3.0
Copyright (c) 2020 Free Software Foundation, Inc.
本程序是自由软件；请参看源代码的版权声明。本软件没有任何担保；
包括没有适销性和某一专用目的下的适用性担保。`

**Comment by Guyutongxue** [comment]
OK 我明白了；当编译器的输出不是 UTF-8 编码的时候（你这里用了 GBK 的中文），程序无法成功解码，所以找不到版本信息。这个 Bug 先记下，你暂时用我的那个 12.2.0 的 GCC；之后有空尝试修复。

**Comment by Guyutongxue** [comment]
@T-Atlas 请尝试 [这个版本](https://github.com/VSCodeConfigHelper/v4/suites/10643607288/artifacts/531708767) 。如果问题解决，我就把这个补丁合并到下一个版本；还有问题的话请继续反馈。

**Comment by T-Atlas** [comment]
> 

问题解决，谢谢
