### ISSUE TITLE
一直都是0%

### ISSUE THREAD

**Issue by caolib** [VSCodeConfigHelper/v4#35]
<h1 style='color:red'>一直都是这个页面，不知道怎么回事，网络是正常的</h1>

![image](https://github.com/VSCodeConfigHelper/v4/assets/102155030/40c650d1-79c4-4a72-a4c7-d29386ed8fd5)

**Comment by chillcicada** [comment]
我今天也遇到了同样的问题，重启一下就解决了。cpptools 安装时会检测编译器环境，猜测可能是 vscch 安装的编译器的环境变量需要重启 vssch 才能生效。
