### ISSUE TITLE
控制台打印中文乱码问题

### ISSUE THREAD

**Issue by lingdiansr** [VSCodeConfigHelper/v4#40]
建议在【配置选项】阶段的功能页中新增一个开关，控制是否在lanch.json文件中的"args"选项添加"-fexec-charset=GBK"，以实现在终端打印中文。

**Comment by Guyutongxue** [comment]
![image](https://github.com/VSCodeConfigHelper/v4/assets/33127223/bf73e515-639f-4213-a171-8c9560554f03)
¯\\_(ツ)_/¯
