### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by LionChenA** [VSCodeConfigHelper/v4#8]
- 对于 mac m1，能否在c_cpp_properties.json中将"intelliSenseMode"自动设置为 macos-clang-arm64，默认为macos-clang-x64。
- 能否提示自动安装的插件列表(Mac 上为C++、CodeLLDB 和 Console Pauser)和配置选项中不推荐的拓展的列表。

**Comment by Guyutongxue** [comment]
1. 理论上可以（在代码上也标记为 TODO），但由于我没有 Apple Silicon 的 Mac，所以不知道准确的写法（比如运行在 Rosetta 2 里的程序是否能正确检测到物理架构）。
2. 安装的插件有：
  - `C/C++`，微软开发的智能提示扩展
  - `CodeLLDB`，用于调试 LLVM 编译出来的目标的扩展（使用 Clang、Apple Clang、LLVM MinGW 时会安装）
  - `Console Pauser`，这个扩展用于 F6 运行时的弹窗功能。目前本来不应该被安装，但由于上个版本（beta 12）发布错误，导致正在开发测试的分支被发布。现在这个版本已经回退掉了，即目前的工具不会安装 `Console Pauser`。等待分支稳定后，该扩展会自动安装。
  - 卸载的插件可在代码中查看：

https://github.com/VSCodeConfigHelper/v4/blob/31cf0c966d0c72a5c186228bf0f0124d4e832f85/src-tauri/src/tasks/extension.rs#L127-L137

如果没有其它问题，可以关闭此 Issue。
